server:
  port: 5000
  servlet:
    encoding:
      charset: utf-8

spring:
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

# S3 이미지 업로드
cloud:
  aws:
    credentials:
      accessKey: ${{ secrets.access.key }}
      secretKey: ${{ secrets.secret.key }}
    s3:
      bucket: ${{ secrets.s3.bucket }}
      url: ${{ secrets.s3.url }}
      region: ${{ secrets.s3.region }}
      stack:
        auto: false

logging:
  level:
    '[org.springframework.boot.web]': INFO

# MyBatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml

# 사업자 검증
api:
  url:
    validate-biz: http://api.odcloud.kr/api/nts-businessman/v1/validate?serviceKey=

service:
  key: ${service.key.validate-biz}