server:
  port: 8081
  servlet:
    encoding:
      charset: utf-8

#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html

spring:
  datasource:
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${rds.username}
    password: ${rds.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    '[org.springframework.boot.web]': DEBUG

# MyBatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml

api:
  url:
    validate-biz: http://api.odcloud.kr/api/nts-businessman/v1/validate?serviceKey=

service:
  key:
    validate-biz: R8ImxtGkuUdDEbDF8oLDNVJjDuWNo9EG6xlzhXjdDvSN20iyo084NDxfTiqATzqBN6z98%2BEFHIShlu3%2Fy%2FhYSA%3D%3D